summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-14.0-arm64/releases/download/2024.06.06/pkg-config-0.29.2-macos-14.0-arm64.tar.xz
bin-sha: 729e559e8cf78251d98d4034158592aa190d011262a866bd220a23fd101330f3
