summary: Keyboard configuration database for the X Window System
webpage: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
version: 2.47
bin-url: https://github.com/leleliu008/uppm-package-repository-macos-14.0-arm64/releases/download/2026.08.12.2/xkeyboard-config-2.47-MacOSX-14.0-arm64.tar.xz
bin-sha: 3ebe269ae6d73cc9fca64406de1fc1905d2e0cf43a5d7048e2538c96e8689743
